<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moses" nsURI="moses" nsPrefix="">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sdn">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
      <details key="onefile" value="true"/>
      <details key="rcp" value="true"/>
      <details key="diagram.extension" value="moses"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//NetworkNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apps" upperBound="-1" eType="#//App"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleObjects" upperBound="-1"
        eType="#//AppObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="ControllerFigure"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/controller.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/host.gif"/>
      <details key="figure" value="HostFigure"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostSwitch" eType="#//Switch">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/switch.gif"/>
      <details key="figure" value="SwitchFigure"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switchController" upperBound="-1"
        eType="#//Controller">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switches" upperBound="-1"
        eType="#//Switch">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
        <details key="switches.constraint" value="self &lt;> oppositeEnd"/>
        <details key="source.constraint" value="self &lt;> oppositeEnd"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//AppObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="RuleFigure"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/policy.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowRule" eType="#//Flow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="App">
    <eAnnotations source="gmf.node">
      <details key="figure" value="ActionFigure"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/action.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appToPacketHeader" upperBound="-1"
        eType="#//PacketHeader">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appToNetworkNode" eType="#//NetworkNode">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerApp" upperBound="-1"
        eType="#//Controller">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appRule" upperBound="-1"
        eType="#//Rule" transient="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="App"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Traffic" eSuperTypes="#//AppObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="TrafficFigure"/>
      <details key="label" value="operator,value,unit"/>
      <details key="label.pattern" value="{0}: {2}{1}"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/traffic.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacketHeader" eSuperTypes="#//AppObject">
    <eAnnotations source="gmf.node">
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="moses.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/packetheader.gif"/>
      <details key="label.placement" value="external"/>
      <details key="label" value="operator,header,value"/>
      <details key="label.pattern" value="{0}: [{1}] {2}"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowSourceHost" eType="#//Host"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowDestinationHost" eType="#//Host"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchFields" eType="#//PacketHeaders"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchValues" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PacketHeaders"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Actions"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Conditions"/>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperators"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AppTypes"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ControllerTypes"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Instructions"/>
</ecore:EPackage>
